In [1]:
import numpy as np

In [9]:
# создание массивов
# сложнейший массив из списка
arr1 = np.array([1, 2, 3, 4])
print(arr1)
# километровая матрица
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)
# нули
zeros = np.zeros((2, 3))
print(zeros)
# единички
ones = np.ones((2, 3))
print(ones)
# округление
rand = np.random.random((2, 3))
rand

[1 2 3 4]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


array([[0.8797278 , 0.72606009, 0.98977476],
       [0.42139613, 0.46978192, 0.21704774]])

In [15]:
# shape и dtype
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype='int64')

print(arr.shape)
arr.dtype

(2, 3)


dtype('int64')

In [ ]:
# индексирование и срезы
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('первая строка:', arr[0])
print('элемент [1,2]:', arr[1, 2])
print('подмассив 2x2:', arr[0:2, 1:3])
print('каждый второй элемент в строке 0:', arr[0, ::2])

первая строка: [1 2 3 4]
элемент [1,2]: 7
подмассив 2x2: [[2 3]
 [6 7]]
каждый второй элемент в строке 0: [1 3]


In [ ]:
# матрицы
a = np.array([[1, 2, 3],[4,5,6]])
b = np.array([[6, 7],[8,9],[10,11]])
print(np.transpose(a)+b,"\n\n",np.transpose(a)*b,"\n\n",np.transpose(a),'\n\n',np.transpose(b))

[[ 7 11]
 [10 14]
 [13 17]] 

 [[ 6 28]
 [16 45]
 [30 66]] 

 [[1 4]
 [2 5]
 [3 6]] 

 [[ 6  8 10]
 [ 7  9 11]]


In [ ]:
# ститистикs
data = np.random.random((3, 4))

print('массив:\n', data)
print('среднее:', np.mean(data))
print('медиана:', np.median(data))
print('максимум:', np.max(data))
print('минимум по столбцам:', np.min(data, axis=0))
print('стандартное отклонение:', np.std(data))

массив:
 [[0.04294282 0.53529406 0.18055629 0.6228487 ]
 [0.91935623 0.93405535 0.49045138 0.61883312]
 [0.2861686  0.40561786 0.92239995 0.28691825]]
среднее: 0.5204535516196244
медиана: 0.5128727204656605
максимум: 0.9340553541619412
минимум по столбцам: [0.04294282 0.40561786 0.18055629 0.28691825]
стандартное отклонение: 0.2856566183709325
